name: Deploy
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Assets
        run: cp package.json dist/package.json

      - name: Publish
        run: cd dist && pnpm publish --access public --publish-branch release
