name: Deploy
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Dependencies
        run: pnpm install

      - name: Build
        run: tsc

      - name: Assets
        run: cp package.json dist/package.json

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd dist && pnpm publish --access public --no-git-checks
